FROM openjdk:11.0-jre-buster
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
COPY ./jar/kapp-core-v1.0.jar /kapp-core-v1.0.jar
ENTRYPOINT ["java","-jar","/kapp-core-v1.0.jar"]